import { useEffect, useState } from "react";
import { Composer } from "./components/Composer.js";
import { MessageList } from "./components/MessageList.js";
import { ResearchTrace } from "./components/ResearchTrace.js";
import { createChatApi, type ChatApi, type ChatEvent, type ChatMessage } from "./lib/chat-api.js";
import "./styles.css";

export function App({ api = createChatApi() }: { api?: ChatApi }) {
  const [chatId, setChatId] = useState<string>(); const [chats, setChats] = useState<Array<{ id: string; pi_session_id: string }>>([]); const [messages, setMessages] = useState<ChatMessage[]>([]); const [draft, setDraft] = useState(""); const [active, setActive] = useState(false); const [connected, setConnected] = useState(true); const [loading, setLoading] = useState(true); const [trace, setTrace] = useState<string[]>([]); const [citations, setCitations] = useState<Array<{ title: string; publishedAt: string; href: string }>>([]); const [error, setError] = useState(""); const [idempotencyKey, setIdempotencyKey] = useState(() => crypto.randomUUID());
  const ensureChat = async () => { if (chatId) return chatId; const chat = await api.createChat(); setChatId(chat.id); setChats((items) => [...items, chat]); return chat.id; };
  useEffect(() => { api.listChats().then((items) => { setChats(items); if (items[0]) setChatId(items[0].id); }).catch(() => setError("无法加载 chat 列表")).finally(() => setLoading(false)); }, []);
  useEffect(() => { let dispose: (() => void) | undefined; if (chatId) { api.getMessages(chatId).then((result) => setMessages((old) => mergeMessages(old, result.messages))).catch(() => setError("无法加载消息")); dispose = api.subscribe(chatId, (event) => handleEvent(event), (online) => { setConnected(online); if (online) api.getMessages(chatId).then((result) => setMessages((old) => mergeMessages(old, result.messages))); }); } return () => dispose?.(); }, [chatId]);
  const handleEvent = (event: ChatEvent) => { if (event.type === "run.started" || event.type === "tool.started") { setActive(true); setTrace((items) => [...items, String(event.data.label ?? event.data.tool_name ?? "研究中")]); } if (event.type === "message.delta") setMessages((items) => { const last = items[items.length - 1]; if (last?.role === "assistant") return [...items.slice(0, -1), { ...last, content: last.content + String(event.data.delta ?? "") }]; return [...items, { id: `stream-${event.id}`, role: "assistant", content: String(event.data.delta ?? "") }]; }); if (event.type === "message.completed") setActive(false); if (event.type === "run.completed" || event.type === "run.cancelled" || event.type === "run.failed") setActive(false); if (event.type === "citation") setCitations((items) => [...items, { title: String(event.data.title ?? event.data.document_id ?? "来源"), publishedAt: String(event.data.published_at ?? ""), href: String(event.data.locator ?? event.data.document_id ?? "#") }]); if (event.type === "run.failed") setError("研究失败"); };
  const send = async () => { if (!draft.trim()) return; try { const id = await ensureChat(); setMessages((items) => [...items, { id: `local-${Date.now()}`, role: "user", content: draft }]); setActive(true); await api.sendMessage(id, draft, idempotencyKey); setDraft(""); setIdempotencyKey(crypto.randomUUID()); } catch { setError("发送失败"); setActive(false); } };
  const stop = async () => { if (chatId) await api.stop(chatId); setActive(false); };
  if (loading) return <main><p role="status">加载中…</p></main>;
  return <main><header><h1>投资研究助手</h1><button onClick={() => { setChatId(undefined); setMessages([]); setTrace([]); setCitations([]); setError(""); setConnected(true); setActive(false); setIdempotencyKey(crypto.randomUUID()); }}>新建 chat</button></header><nav aria-label="chat 列表">{chats.map((chat) => <button key={chat.id} aria-pressed={chat.id === chatId} onClick={() => setChatId(chat.id)}>{chat.id}</button>)}</nav>{!connected && <p role="status">连接已断开，正在重连…</p>}{error && <p role="alert">{error}</p>}<MessageList messages={messages} /><ResearchTrace items={trace} citations={citations} /><Composer value={draft} onChange={setDraft} onSend={send} onStop={stop} active={active} /></main>;
}

function mergeMessages(existing: ChatMessage[], incoming: ChatMessage[]) { const map = new Map(existing.map((message) => [message.id, message])); incoming.forEach((message) => map.set(message.id, message)); return [...map.values()]; }
